# 一、异常

## 1. 异常捕获

### 完整语法

```python
try:
    # 尝试执行的代码
    pass
except 错误类型1:
    # 针对错误类型1，对应的代码处理
    pass
except 错误类型2:
    # 针对错误类型2，对应的代码处理
    pass
except (错误类型3, 错误类型4):
    # 针对错误类型3 和 4，对应的代码处理
    pass
except Exception as result:
    # 打印错误信息
    print(result)
else:
    # 没有异常才会执行的代码
    pass
finally:
    # 无论是否有异常，都会执行的代码
    print("无论是否有异常，都会执行的代码")
```



## 2. 抛出 `raise` 异常

```python
def input_password():

    # 1. 提示用户输入密码
    pwd = input("请输入密码：")

    # 2. 判断密码长度，如果长度 >= 8，返回用户输入的密码
    if len(pwd) >= 8:
        return pwd

    # 3. 密码长度不够，需要抛出异常
    # 1> 创建异常对象 - 使用异常的错误信息字符串作为参数
    ex = Exception("密码长度不够")

    # 2> 抛出异常对象
    raise ex


try:
    user_pwd = input_password()
    print(user_pwd)
except Exception as result:
    print("发现错误：%s" % result)
```



# 二、 断言

- assert 断言 后面是一个表达式，如果表达式返回真，则断言成功，程序能后继续往下执行
- 如果表达式返回假，则断言失败，assert会抛出异常AssertionError，终止程序继续往下执行

```python
import sys
assert ('linux' in sys.platform), "该代码只能在 Linux 下执行"
```

```python
def num_div(num1, num2):
    assert isinstance(num1,int),"num1 应为整数"
    assert isinstance(num2,int),"num1 应为整数"
    assert num2!=0,"num2不能为0"
    print(num1 / num2)
```

